config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :categories

  resources :tasks do
    collection do
      patch 'finish'
    end
    member do
      patch 'continue'
    end
  end

  root 'tasks#index'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  
  validates :user, presence: true

  scope :for_user, ->(user) { where(user: user) }  
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :category, presence: true
  validates :start, presence: true
  validates :user, presence: true

  scope :currents, ->(user) { where(user: user).where(finish: nil) }
  scope :to_date, ->(date, user) { where(user: user).where("start >= '#{date.beginning_of_day}'").where("start <= '#{date.end_of_day}'").order(start: :asc) }
  scope :for_user, ->(user) { where(user: user) }
  scope :per_categories, ->(user) {select('categories.name as category_name, sum(finish - start) as during').joins(:category).group('categories.name').where(user: user).where("start >= '#{Time.now.beginning_of_day}'").where("start <= '#{Time.now.end_of_day}'").order('during DESC')}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  around_action :user_time_zone

  def user_time_zone(&block)
    user_zone = current_user ? current_user.time_zone : 'UTC'
    Time.use_zone(user_zone, &block)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.for_user(current_user)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.for_user(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :continue]

  # GET /tasks
  # GET /tasks.json
  def index
    date_param = params[:date]
    tasks_date = date_param ? Time.parse(date_param) : Time.now
    @tasks = Task.to_date(tasks_date, current_user)
    @task = Task.new
    @current_task = Task.currents(current_user).first
    @statistics = Task.per_categories(current_user)
  end

  def continue
    finish_current_task
    Task.create(
      category: @task.category,
      description: @task.description,
      user: current_user,
      start: Time.now
    )

    redirect_to action: 'index'
  end

  def finish
    finish_current_task
    redirect_to action: 'index'
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.start = Time.now
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to action: 'index' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to action: 'index', notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.for_user(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :category_id, :start, :finish)
    end

    def finish_current_task
      @current_task = Task.currents(current_user).first
      return if !@current_task
      @current_task.finish = Time.now
      @current_task.save
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  #  super
  #end

  # POST /resource/sign_in
  def create
    super
    user = User.find_by_email(params[:user][:email])
    user.update(time_zone: params[:user][:time_zone]) if user
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.haml
= bootstrap_form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name
  .actions
    = f.submit 'Save', :class=>"btn btn-success"

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories
.panel.panel-default
  .panel-body
    = link_to 'New Category', new_category_path, class: "btn btn-success"

    %table.table
      %thead
        %tr
          %th Name
          %th
          %th
          %th

      %tbody
        - @categories.each do |category|
          %tr
            %td= category.name
            %td= link_to 'Show', category
            %td= link_to 'Edit', edit_category_path(category)
            %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustTracker</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/shared/menu' %>

    <div class="main-form container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/settings/index.html.haml
%h1 Settings

= form_tag settings_update_path, method: :post do
  .field
    %label{class: 'control-label'}
      Time zone
    = text_field_tag :time_zone, @time_zone, :class=>"form-control"
  %br
  .actions
    = submit_tag 'Update', :class=>"btn btn-success"

app/views/shared/_menu.html.haml
.navbar.navbar-inverse.navbar-fixed-top{:role=>'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle{:type=>"button", 'data-toggle'=>'collapse', 'data-target'=>'.navbar-collapse'}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
  
      %a{:class=>"navbar-brand #{'color_menu' if controller_name == 'tasks'}", :href=>"/"}
        %span{class: 'glyphicon glyphicon-thumbs-up'}
        Just Tracker

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{:class=>"#{'active' if controller_name == 'tasks'}"}
          = link_to "Tasks", tasks_path
  
      %ul.nav.navbar-nav
        %li{:class=>"#{'active' if controller_name == 'categories' }"}
          = link_to "Categories", categories_path
  
      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          %li
            = link_to "#{current_user.email}"
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "SignUp", new_user_registration_path

app/views/tasks/_form.html.haml
= bootstrap_form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  = f.label :start
  .input-group.date.form-group
    = f.text_field :start, :hide_label => true, :readonly => true
    %span{class: 'input-group-addon'}
      %span{class: 'glyphicon glyphicon-calendar'}

  = f.label :finish
  .input-group.date.form-group
    = f.text_field :finish, :hide_label => true, :readonly => true

    %span{class: 'input-group-addon'}
      %span{class: 'glyphicon glyphicon-calendar'}


  .field
    = f.collection_select :category_id, Category.for_user(current_user), :id, :name
  .field
    = f.text_area :description

  .actions
    = f.submit 'Save Task', :class=>"btn btn-success"

app/views/tasks/_short_form.html.haml
%h1 New Task
.panel.panel-default
  .panel-body
    = bootstrap_form_for @task do |f|
      - if @task.errors.any?
        #error_explanation
          %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
          %ul
            - @task.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.collection_select :category_id, Category.for_user(current_user), :id, :name
      .field
        = f.text_field :description

      .actions
        = f.submit 'Start New Task', :class=>"btn btn-success"

app/views/tasks/_short_view.html.haml
%h1 Current Task
.panel.panel-default
  .panel-body
    %p 
      %b Category: 
      = @current_task.category.name
    %p
      %b Start:
      = @current_task.start.strftime('%F %H:%M')
    - if !@current_task.description.empty?
      %p 
        %b Description:
        = @current_task.description


    = link_to 'Finish', finish_tasks_path, method: :patch, :class=>"btn btn-success"

app/views/tasks/_view.html.haml
%li
  .task-body
    .task-time
      = task.start.strftime('%H:%M')
      &ndash;
      = task.finish ? task.finish.strftime('%H:%M') : 'Now'
  
    %div
      %h4
        = task.category.name
    %div
      = task.description

  .task-buttons
    %ul{class: 'list-inline item-icons'}
      %li
        = link_to continue_task_path(task), :method => :patch, title: 'Continue' do
          %i{class: 'glyphicon glyphicon-play-circle'}
      
      %li
        = link_to edit_task_path(task), title: 'Edit' do
          %i{class: 'glyphicon glyphicon-pencil'}

      %li
        = link_to task, :method => :delete, :data => { :confirm => 'Are you sure?' }, title: 'Destroy' do
          %i{class: 'glyphicon glyphicon-remove'}

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'To List', tasks_path

app/views/tasks/index.html.haml
.row
  .col-xs-12.col-sm-12.col-md-9
    - if @current_task
      = render 'short_view'
    - else
      = render 'short_form'

    %h1{id: 'taks-caption'} Today Tasks

    .panel.panel-default
      .panel-body
        #tasks-t-body
          %ul{class: 'items-list'}
            - @tasks.each do |task|
              = render partial: 'view', locals: { task: task }
  .col-xs-12.col-sm-12.col-md-3
    %h2 For date:
    .panel.panel-default
      .panel-body
        #task_datetimepicker

    %h2 Statistics:
    %ul{class: 'list-group'}
      - @statistics.each do |stat_item|
        %li{class: 'list-group-item'}
          = stat_item.category_name
          %span{class: 'badge'}
            = stat_item.during.to_s.truncate(8, omission: '')

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>